version: "3.9"

services:
  # ───────────────────────── MongoDB ─────────────────────────
  mongo:
    image: mongo:7
    container_name: frontline_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ───────────────────────── Auth ────────────────────────────
  auth:                           # ◀ OUTDENT to same level as mongo
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file: ./services/auth/.env
    environment:
      UPLOAD_DIR: /home/node/uploads
    depends_on:                   # ◀ no “condition” in Compose v3.9
      - mongo
    volumes:
      - auth-uploads:/home/node/uploads
    ports:
      - "4000:4000"

  # ───────────────────────── Messaging ───────────────────────
  messaging:
    build:
      context: .
      dockerfile: services/messaging/Dockerfile
    env_file: ./services/messaging/.env
    environment:               # ← add this block
      - UPLOAD_DIR=/home/node/uploads
      - BYPASS_AUTH=1          # still in dev mode
    volumes:                   # ← and this
      - messaging-uploads:/home/node/uploads
    depends_on: [mongo, auth]
    ports: ["5000:5000"]

  # ───────────────────────── Task ────────────────────────────
  task:
    build:
      context: .
      dockerfile: services/task/Dockerfile
    env_file: ./services/task/.env
    depends_on:
      - mongo
      - auth
    ports:
      - "5001:5001"

  # ───────────────────────── Alert ────────────────────────────
  alert:
    build:
      context: .
      dockerfile: services/alert/Dockerfile
    env_file: ./services/alert/.env
    environment:
      UPLOAD_DIR: /home/node/uploads        # ◀ map–style for consistency
    volumes:
      - alert-uploads:/home/node/uploads
    depends_on:
      - mongo
      - auth
    ports:
      - "5100:5100"

  # ───────────────────────── Announcement ────────────────────
  announcement:
    build:
      context: .
      dockerfile: services/announcement/Dockerfile
    env_file: ./services/announcement/.env
    environment:
      UPLOAD_DIR: /home/node/uploads
    volumes:
      - announcement-uploads:/home/node/uploads
    depends_on:
      - mongo
      - auth
    ports:
      - "5200:5200"

  # ───────────────────────── Shift ────────────────────────────
  shift:
    build:
      context: .
      dockerfile: services/shift/Dockerfile
    env_file: ./services/shift/.env
    environment:
      UPLOAD_DIR: /home/node/uploads
    volumes:
      - shift-uploads:/home/node/uploads
    depends_on:
      - mongo
      - auth
    ports:
      - "5300:5300"

# ───────────────────────── Volumes ───────────────────────────
volumes:
  mongo-data:
  auth-uploads:
  alert-uploads:
  announcement-uploads:
  shift-uploads:
  messaging-uploads: 