version: '3.8'
services:
  auth-service:
    build: .
    container_name: auth_microservice
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://db:27017/auth_service_dev
      - JWT_SECRET=MySuperSecretKey
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: auth_db
    ports:
      - "27017:27017"
