version: '3.8'
services:
  auth-service:
    build: .
    container_name: auth_microservice
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=auth_service_dev
      - JWT_SECRET=MySuperSecretKey  # <--- add your secret here
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: auth_service_dev
    ports:
      - "5432:5432"
